config/routes.rb
MongoidForums::Engine.routes.draw do

  namespace :admin do
    root :to => 'base#index'
    resources :forums do
      post '/add_group' => 'forums#add_group', as: :add_group
      post '/rem_group' => 'forums#remove_group', as: :rem_group
    end
    resources :categories do
      post '/add_group' => 'categories#add_group', as: :add_group
      post '/rem_group' => 'categories#remove_group', as: :rem_group
    end
    resources :groups do
      post '/add_user' => 'groups#add_member', as: :add_user
      post '/rem_user' => 'groups#remove_member', as: :rem_user
    end

    resources :topics do
      member do
        get 'toggle_hide' => 'topics#toggle_hide', :as => 'toggle_hide'
        get 'toggle_lock' => 'topics#toggle_lock', :as => 'toggle_lock'
        get 'toggle_pin' => 'topics#toggle_pin', :as => 'toggle_pin'
      end
    end

    resources :users do
      post '/add' => 'users#add_admin', as: 'add_admin'
      post '/remove' => 'users#remove_admin', as: 'remove_admin'
    end
  end

  root :to => "forums#index"

  # REDIRECT OLD ROUTES
  get '/forums/:forum_id/', :to => "redirect#forum"
  get '/forums/:forum_id/topics/:topic_id', :to => "redirect#topic"
  get '/posts/:post_id', :to => "redirect#posts"
  get '/subscriptions', :to => "redirect#subscriptions"


  # ME ROUTES
  get 'my_subscriptions', :to => "topics#my_subscriptions"
  get 'my_topics', :to => "topics#my_topics"
  get 'my_posts', :to => "topics#my_posts"

  # this moves the creation of topics into /forum_id/new
  resources :forums, :path => "/" do
    get 'new'
    post 'create'
  end

  resources :topics, :path => "/topics" do
    resources :posts
    member do
      get :subscribe
      get :unsubscribe
    end
  end

  resources :categories

end

app/models/mongoid_forums/group.rb
module MongoidForums
  class Group
    include Mongoid::Document

    validates :name, :moderator, :presence => true

    field :name, type: String
    field :moderator, type: Boolean
    field :members, type: Array, default: []

    def to_s
      name
    end
  end
end

app/controllers/mongoid_forums/admin/groups_controller.rb
require_dependency "mongoid_forums/application_controller"

module MongoidForums
  module Admin
    class GroupsController < BaseController

      def index
        @groups = Group.all
      end

      def new
        @group = Group.new
      end

      def create
        @group =  Group.new(params.require(:group).permit(:name, :moderator, :members))
        if @group.save
          flash[:notice] = t("mongoid_forums.admin.group.created")
          redirect_to [:admin, @group]
        else
          flash[:notice] = t("mongoid_forums.admin.group.not_created")
          render :action => "new"
        end
      end

      def edit
        @group = Group.find(params[:id])
      end

      def update
        @group = Group.find(params[:id])
        if @group.update_attributes(params.require(:group).permit(:name, :members))
          flash[:notice] = t("mongoid_forums.admin.group.updated")
          redirect_to [:admin, @group]
        else
          flash[:notice] = t("mongoid_forums.admin.group.not_updated")
          render :action => "edit"
        end
      end

      def show
        @group = Group.find(params[:id])
        @group_members = @group.members.map{|member_id| User.find(member_id) }
        @users = User.all.select{ |user| !@group.members.include?(user.id) }
      end

      def destroy
        @group = Group.find(params[:id])
        @group.destroy
        flash[:notice] = t("mongoid_forums.admin.group.deleted")
        redirect_to admin_groups_path
      end

      ### Temporary Methods - Try Not To Cringe Too Much <3 ###
      def add_member
        group = Group.find(params.require(:group_id))
        user = User.find(params[:user][:id])

        group.members << user.id unless group.members.include?(user.id)
        group.save

        redirect_to admin_group_path(group)
      end

      def remove_member
        group = Group.find(params.require(:group_id))
        user = User.find(params[:user][:id])

        group.members.delete(user.id)
        group.save

        redirect_to admin_group_path(group)
      end
      #########################################################
    end

    private

    def group_params
      params.require(:group).permit(:name, :members)
    end
  end
end

app/helpers/mongoid_forums/admin/groups_helper.rb
module MongoidForums
  module Admin::GroupsHelper
  end
end

app/views/mongoid_forums/admin/groups/edit.haml
= simple_form_for [:admin, @group] do |f|
  = f.input :name
  = f.input :moderator, as: :radio_buttons
  = f.submit "Update Group", :class => "btn", :disable_with => "Creating..."

app/views/mongoid_forums/admin/groups/index.haml
%h1 Manage groups

%h2 Create a new group
= link_to "New group", new_admin_group_path

%h2 Listing all groups
%table{:border => "1"}
  %tr
    %th
      Name
    %th
      Moderator

  - @groups.each_with_index do |group, i|
    %tr
      %td
        = link_to group.name, [:admin, group]
      %td
        = group.moderator
      %td
        = link_to "Edit", edit_admin_group_path(group)
      %td
        = button_to "Destroy", admin_group_path(group), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }

app/views/mongoid_forums/admin/groups/new.haml
// create a new mod group OR create a new group
= simple_form_for [:admin, @group] do |f|
  = f.input :name
  = f.input :moderator, as: :radio_buttons
  = f.submit "Create Group", :class => "btn", :disable_with => "Creating..."

app/views/mongoid_forums/admin/groups/show.haml
%h2
  = @group.name
%h3 Listing all members
%table{:border => "1"}
  %tr
    %th
      Name

  - @group.members.each do |member|
    %tr
      %td
        = MongoidForums.user_class.find(member).forum_display_name
      %td
        = button_to "Remove", admin_group_rem_user_path(group_id: @group.id, user: {id: member}), method: :post, data: { confirm: 'Are you certain you want to delete this?' }

= form_tag admin_group_add_user_path(@group), :method => :post, :id => "form_add_user" do
  %input{:id => "userinput", :list => "users", :name => "[user][id]"}/
  %datalist#users
    - @users.each do |user|
      %option{:id => user.id, :value => user.forum_display_name}
  = submit_tag("Add User")

:javascript
  $("#form_add_user").submit(function(){
    $("#userinput").val($('#users').find('option[value="' + $('#userinput').val() + '"]').attr('id'));
  });