config/routes.rb
MongoidForums::Engine.routes.draw do

  namespace :admin do
    root :to => 'base#index'
    resources :forums do
      post '/add_group' => 'forums#add_group', as: :add_group
      post '/rem_group' => 'forums#remove_group', as: :rem_group
    end
    resources :categories do
      post '/add_group' => 'categories#add_group', as: :add_group
      post '/rem_group' => 'categories#remove_group', as: :rem_group
    end
    resources :groups do
      post '/add_user' => 'groups#add_member', as: :add_user
      post '/rem_user' => 'groups#remove_member', as: :rem_user
    end

    resources :topics do
      member do
        get 'toggle_hide' => 'topics#toggle_hide', :as => 'toggle_hide'
        get 'toggle_lock' => 'topics#toggle_lock', :as => 'toggle_lock'
        get 'toggle_pin' => 'topics#toggle_pin', :as => 'toggle_pin'
      end
    end

    resources :users do
      post '/add' => 'users#add_admin', as: 'add_admin'
      post '/remove' => 'users#remove_admin', as: 'remove_admin'
    end
  end

  root :to => "forums#index"

  # REDIRECT OLD ROUTES
  get '/forums/:forum_id/', :to => "redirect#forum"
  get '/forums/:forum_id/topics/:topic_id', :to => "redirect#topic"
  get '/posts/:post_id', :to => "redirect#posts"
  get '/subscriptions', :to => "redirect#subscriptions"


  # ME ROUTES
  get 'my_subscriptions', :to => "topics#my_subscriptions"
  get 'my_topics', :to => "topics#my_topics"
  get 'my_posts', :to => "topics#my_posts"

  # this moves the creation of topics into /forum_id/new
  resources :forums, :path => "/" do
    get 'new'
    post 'create'
  end

  resources :topics, :path => "/topics" do
    resources :posts
    member do
      get :subscribe
      get :unsubscribe
    end
  end

  resources :categories

end

app/models/mongoid_forums/category.rb
module MongoidForums
  class Category
    include Mongoid::Document

    has_many :forums, :class_name => "MongoidForums::Forum",  dependent: :destroy
    has_and_belongs_to_many :moderator_groups, :class_name => "MongoidForums::Group", inverse_of: nil


    field :name
    validates :name, :presence => true

    field :position, :type => Integer, :default => 0
    validates :position, numericality: { only_integer: true }

    def moderator?(user)
      return false unless user
      moderator_groups.each do |group|
        return true if group.moderator && group.members.include?(user.id)
      end
      false
    end

    def moderators
      array = Array.new
      self.moderator_groups.each do |g|
        array << g.group.members
      end
      return array
    end
  end
end

app/controllers/mongoid_forums/admin/categories_controller.rb
require_dependency "mongoid_forums/application_controller"

module MongoidForums
  module Admin
    class CategoriesController < BaseController
      before_action :set_category, only: [:add_group, :remove_group]

      def index
        @forums = Forum.asc(:position)
        @categories = Category.asc(:position)
      end

      def show
        @category = Category.find(params[:id])
        @groups = Group.  all.where(moderator: true).select{ |group| !@category.moderator_groups.include?(group) }
      end

      def new
        @category = Category.new
      end

      def create
        if @category = Category.create(category_params)
          flash[:notice] = t("mongoid_forums.admin.category.created")
          redirect_to admin_categories_path
        else
          flash.now.alert = t("mongoid_forums.admin.category.not_created")
          render :action => "new"
        end
      end

      def edit
        @category = Category.find(params[:id])
      end

      def update
        @category = Category.find(params[:id])
        if @category.update(category_params)
          flash[:notice] = t("mongoid_forums.admin.category.updated")
          redirect_to admin_categories_path
        else
          flash[:notice] = t("mongoid_forums.admin.category.not_updated")
          render :action => "edit"
        end
      end

      def destroy
        @category = Category.find(params[:id])
        @category.destroy
        flash[:notice] = t("mongoid_forums.admin.category.deleted")
        redirect_to admin_categories_path
      end

      ### Temporary Methods - Try Not To Cringe Too Much <3 ###
      def add_group
        group = Group.find(params[:group][:id])
        @category.moderator_groups << group
        @category.save

        redirect_to admin_category_path(@category)
      end

      def remove_group
        group = Group.find(params[:group][:id])
        @category.moderator_groups.delete(group)
        @category.save

        redirect_to admin_category_path(@category)
      end
      #########################################################

      private

      def category_params
        params.require(:category).permit(:name, :position)
      end

      def set_category
        @category = Category.find(params[:category_id])
      end
    end
  end
end

app/helpers/mongoid_forums/admin/categories_helper.rb
module MongoidForums
  module Admin::CategoriesHelper
  end
end

app/views/mongoid_forums/admin/categories/edit.haml
= simple_form_for [:admin, @category] do |f|
  = f.input :name
  = f.input :position
  = f.submit "Update Category", :class => "btn", :disable_with => "Updating..."

app/views/mongoid_forums/admin/categories/index.haml
%h1 Manage categories

%h2 Create a new category
= link_to "New category", new_admin_category_path

%h2 Listing all categories
%table{:border => "1"}
  %tr
    %th
      Name

  - @categories.each do |category|
    %tr
      %td
        = link_to category.name, [:admin, category]
      %td
        = link_to "Show", admin_category_path(category)
      %td
        = link_to "Edit", edit_admin_category_path(category)
      %td
        = button_to "Destroy", admin_category_path(category), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }

app/views/mongoid_forums/admin/categories/new.haml
= simple_form_for [:admin, @category] do |f|
  = f.input :name
  = f.input :position
  = f.submit "Create Category", :class => "btn", :disable_with => "Creating..."

app/views/mongoid_forums/admin/categories/show.haml
%h2 Listing all moderator groups for: #{@category.name}
%table{:border => "1"}
  %tr
    %th
      Name

  - @category.moderator_groups.each do |group|
    %tr
      %td
        = link_to group.name, [:admin, group]
      %td
        = link_to "Show", admin_group_path(group)
      %td
        = link_to "Edit", edit_admin_group_path(group)
      %td
        = button_to "Remove", admin_category_rem_group_path(category_id: params[:id], group: {id: group.id}), method: :post, data: { confirm: 'Are you certain you want to delete this?' }

= form_tag admin_category_add_group_path(@category), :method => :post do
  = collection_select(:group, :id, @groups, :id, :name, {:prompt => true})
  %button
    Add