config/routes.rb
MongoidForums::Engine.routes.draw do

  namespace :admin do
    root :to => 'base#index'
    resources :forums do
      post '/add_group' => 'forums#add_group', as: :add_group
      post '/rem_group' => 'forums#remove_group', as: :rem_group
    end
    resources :categories do
      post '/add_group' => 'categories#add_group', as: :add_group
      post '/rem_group' => 'categories#remove_group', as: :rem_group
    end
    resources :groups do
      post '/add_user' => 'groups#add_member', as: :add_user
      post '/rem_user' => 'groups#remove_member', as: :rem_user
    end

    resources :topics do
      member do
        get 'toggle_hide' => 'topics#toggle_hide', :as => 'toggle_hide'
        get 'toggle_lock' => 'topics#toggle_lock', :as => 'toggle_lock'
        get 'toggle_pin' => 'topics#toggle_pin', :as => 'toggle_pin'
      end
    end

    resources :users do
      post '/add' => 'users#add_admin', as: 'add_admin'
      post '/remove' => 'users#remove_admin', as: 'remove_admin'
    end
  end

  root :to => "forums#index"

  # REDIRECT OLD ROUTES
  get '/forums/:forum_id/', :to => "redirect#forum"
  get '/forums/:forum_id/topics/:topic_id', :to => "redirect#topic"
  get '/posts/:post_id', :to => "redirect#posts"
  get '/subscriptions', :to => "redirect#subscriptions"


  # ME ROUTES
  get 'my_subscriptions', :to => "topics#my_subscriptions"
  get 'my_topics', :to => "topics#my_topics"
  get 'my_posts', :to => "topics#my_posts"

  # this moves the creation of topics into /forum_id/new
  resources :forums, :path => "/" do
    get 'new'
    post 'create'
  end

  resources :topics, :path => "/topics" do
    resources :posts
    member do
      get :subscribe
      get :unsubscribe
    end
  end

  resources :categories

end

app/controllers/mongoid_forums/admin/users_controller.rb
require_dependency "mongoid_forums/application_controller"

module MongoidForums
  module Admin
    class UsersController < BaseController

      before_action :set_user, only: [:add_admin, :remove_admin]

      def index
        @admins = User.where(mongoid_admin: true)
        @non_admins = User.where(mongoid_admin: false)
      end

      def add_admin
        @user.mongoid_admin = true
        @user.save
        redirect_to admin_users_path
      end

      def remove_admin
        @user.mongoid_admin = false
        @user.save
        redirect_to admin_users_path
      end

      private

      def set_user
        @user = User.find(params[:user][:id])
      end

    end
  end
end

app/helpers/mongoid_forums/admin/users_helper.rb
module MongoidForums
  module Admin::UsersHelper
  end
end

app/views/mongoid_forums/admin/users/index.haml
%h3 Listing all admins
%table{:border => "1"}
  %tr
    %th
      Name

  - @admins.each do |admin|
    %tr
      %td
        = admin.forum_display_name
      %td
        = button_to "Remove", admin_user_remove_admin_path("dummy", user: {id: admin.id}), method: :post, data: { confirm: 'Are you certain you want to delete this?' }

= form_tag admin_user_add_admin_path("dummy"), :method => :post, :id => "form_add_user" do
  %input{:id => "userinput", :list => "users", :name => "[user][id]"}/
  %datalist#users
    - @non_admins.each do |user|
      %option{:id => user.id, :value => user.forum_display_name}
  = submit_tag("Add Admin")

:javascript
  $("#form_add_user").submit(function(){
    $("#userinput").val($('#users').find('option[value="' + $('#userinput').val() + '"]').attr('id'));
  });